### ISSUE TITLE
测试状态更新不正确

### ISSUE THREAD

**Issue by guolong123** [kit101/drone-plugin-gitee-pulls#1]
【描述】
drone在clone时失败了，但最后的comment状态将测试状态改成了全部通过
![image](https://user-images.githubusercontent.com/22833963/180685275-98a06fe4-a3ef-40c0-8bd0-0740ff3424d4.png)
![image](https://user-images.githubusercontent.com/22833963/180685962-269dd6b5-3803-48fe-a810-4fb43596f16a.png)

drone配置：
```yaml
name: keta-ci
kind: pipeline
type: kubernetes
clone:
  depth: 50
#  disable: false

volumes:
  - name: frontend-cache
    host:
      path: /disk2/drone-cache/frontend-cache

  - name: backend-gradle-cache
    host:
      path: /disk2/drone-cache/backend-gradle-cache

  - name: backend-gradle-static-check-cache
    host:
      path: /disk2/drone-cache/backend-gradle-static-check-cache

  - name: backend-gradle-cache-unittest
    host:
      path: /disk2/drone-cache/backend-gradle-cache-unittest

steps:
  - name: comment-status-start
    pull: always

    image: kit101z/drone-plugin-gitee-pulls
    settings:
      # should set `is_running: true` in the first step
      is_running: true
      access_token:
        from_secret: GITEE_TOKEN
    when:
      event:
        - pull_request

  - name: keta-app-clone
    image: drone/git:latest
    commands:
      - git clone https://gitee.com/xishuhq/keta-apps.git pandora/pandora-sub-modules/pdr-apps
      - cd pandora/pandora-sub-modules/pdr-apps && git checkout app_dev

  - name: frontend-ci
    image: ccr.ccs.tencentyun.com/xishuhq/node-jdk:0228175701
    commands:
      - |
        #! /bin/bash
        . scripts/util.sh && needRun "frontend/.*" 
        cur=$PWD
        cd $cur/frontend && rush install && rush prettier
        cd $cur/frontend/packages/webapp && npm run build:dll"
        cd $cur/frontend && rush build -v && rush lint"
    resources:
      limits:
        cpu: 4000
        memory: 8GiB
    volumes:
      - name: frontend-cache
        path: /drone/src/frontend/common/temp
      - name: frontend-npm-cache
        path: /drone/src/.pnpm-store/
    when:
      event:
        - pull_request

  - name: backend-build
    image: ccr.ccs.tencentyun.com/xishuhq/node-jdk:0228175701
    commands:
      - |
        #! /bin/bash
        . scripts/util.sh && needRun "\.java$\|gradle"
        ./gradlew tar -Dtarget=server --parallel
    resources:
      limits:
        cpu: 4000
        memory: 8GiB
    volumes:
      - name: backend-gradle-cache
        path: /root/.gradle
    when:
      event:
        - pull_request
    depends_on:
      - keta-app-clone

  - name: backend-ci-unittest
    image: openjdk:11.0.11
    resources:
      limits:
        cpu: 6000
        memory: 12GiB
    commands:
      - |
        #! /bin/bash
        . scripts/util.sh && needRun "\.java$\|gradle"
      - echo "占用资源过高，暂时停止运行"
#      - cp scripts/init.gradle /root/.gradle
#      - ./gradlew jacocoTestCoverageVerification -Des.insecure.allow.root=true --parallel
    volumes:
      - name: backend-gradle-cache-unittest
        path: /root/.gradle
    when:
      event:
        - pull_request

  - name: backend-ci-static-check
    image: openjdk:11.0.11
    resources:
      limits:
        cpu: 2000
        memory: 4GiB
    commands:
      - | 
        #! /bin/bash 
        . scripts/util.sh && needRun "\.java$\|gradle"
        cp scripts/init.gradle /root/.gradle
        ./gradlew verifyGoogleJavaFormat --parallel
    volumes:
      - name: backend-gradle-static-check-cache
        path: /root/.gradle
    when:
      event:
        - pull_request

  - name: comment-status-end
    image: kit101z/drone-plugin-gitee-pulls
    depends_on:
      - frontend-ci
      - backend-ci-unittest
      - backend-ci-static-check
      - backend-build
    settings:
      access_token:
        from_secret: GITEE_TOKEN
    when:
      event:
        - pull_request
      status:
        - failure
        - success


```
